redis.host=localhost
redis.port=6379
redis.password=
redis.database=0
redis.connectionPoolSize = 10
redis.connectionMinimumIdleSize = 5
redis.connectTimeout = 10000
redis.retryAttempts = 3
redis.retryInterval = 1500